name: know_your_time
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  google_sign_in: ^5.4.0
  fluttertoast: ^8.0.9
  firebase_auth: ^3.5.0
  core:
    path: core
  core_ui:
    path: core_ui
  domain:
    path: domain
  firebase_core: ^1.20.0
  cloud_firestore: ^3.4.0
  provider: ^6.0.3
  flutter:
    sdk: flutter
  data:
    path: data

  tracker_board_view:
    path: features/tracker_board_view

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  dart_code_metrics: ^4.15.0

flutter:
  uses-material-design: true
  assets:
    # images
    - assets/images/image-jeremy.png
    - assets/images/flutter_logo.png
    - assets/images/google_icon.png
    # icons
    - assets/icons/icon-ellipsis.svg
    - assets/icons/icon-exercise.svg
    - assets/icons/icon-play.svg
    - assets/icons/icon-self-care.svg
    - assets/icons/icon-social.svg
    - assets/icons/icon-study.svg
    - assets/icons/icon-work.svg
    # translations
    - assets/translations/en-US.json

  #fonts
  fonts:
    - family: Rubic
      fonts:
        - asset: assets/fonts/rubic/Rubik-Light.ttf
          weight: 300
        - asset: assets/fonts/rubic/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/rubic/Rubik-Medium.ttf
          weight: 500